display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000
  environment_variables: []
  operator: true
  labels:
    app: ska-mid-cbf-tdc-mcs
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  vnc:
    enabled: false
  tangorest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false

ska-mid-cbf-engineering-console:
  enabled: true
  # Uncomment the section below to use custom Engineering Console image
  # engineeringconsole:
  #   image:
  #     registry: registry.gitlab.com/ska-telescope/ska-mid-cbf-engineering-console
  #     image: ska-mid-cbf-engineering-console
  #     tag: <dev tag from EC pipeline>
  #     pullPolicy: IfNotPresent

ska-taranta:
  enabled: false

ska-taranta-auth:
  enabled: false

ska-dashboard-repo:
  enabled: false
