apiVersion: v2
name: ska-mid-cbf-tdc-tmleafnode
description: A Helm chart to deploy tmleafnode simulators for Mid CBF for testing purposes.
version: 1.1.3
appVersion: 1.1.3
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-tango-util
  version: 0.4.13
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-base
  version: 0.4.13
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-tango-base.enabled,global.sub-system.ska-tango-base.enabled


